### PR TITLE
docs: implement `enum` type inside and outside of `message`

### PR DESCRIPTION
**Pull request by imballinst**
This PR implements the `enum` type, which can reside either inside a `message` block or outside of it. Cases tested:

1. Enum inside message
2. Enum outside message
3. Enum without alias
4. Enum with alias

Some of other changes:

1. Remove the redundant `protosaurus` keyword in the package names
2. Always have double new lines after every field
3. Refactor some of the typings to better accommodate the `enum` typing, e.g. `MessageData` to `ObjectData`.

image

Signed-off-by: Try Ajitiono <ballinst@gmail.com>

### CODE REVIEW

**Comment by imballinst** [comment]
Hm, that's weird. Why do I get this error @dio?

```
testdata/booking/v1/booking.proto:88:5:Enum option "allow_alias" on enum "JourneyStatus" must be false.
make: *** [Makefile:149: /home/runner/work/protosaurus/protosaurus/.cache/buf/v1/module/data/buf.build] Error 100
```

Doing `make gen` in my local seems fine...

EDIT: nevermind, I just cleared the top-level `.cache` and now I get the same error

**Comment by imballinst** [comment]
If I do this:

```protobuf
enum JourneyStatus {
  option allow_alias = false;
  UNKNOWN = 0;
  STARTED = 1;
  DEPARTED = 1;
  ARRIVED = 2;
}
```

I get this error instead:

```
testdata/booking/v1/booking.proto:81:16:enum Booking.JourneyStatus: values STARTED and DEPARTED both have the same numeric value 1; use allow_alias option if intentional
```

What might be the issue here?

**Comment by imballinst** [comment]
OK, I figured out that it's because of the buf.build linter: https://docs.buf.build/lint/configuration. I disabled the `ENUM_NO_ALLOW_ALIAS` linter and it would seem to work, at least in my local.

It's interesting because https://developers.google.com/protocol-buffers/docs/proto3#enum has no mentions of "legacy" for `allow_alias` but buf.build does: https://docs.buf.build/lint/configuration#allow_comment_ignores

> "For example, say we have a legacy enum that uses allow_alias."

**Comment by dio** [comment]
Ah sorry just saw this. Glad that you work on allow_alias. Need to put this in a note.

**Comment by dio** [comment]
~Do we have an enum example when it is not nested, but being used in a message?~ Ah sorry we have `BookingStatus`.

**Comment by imballinst** [comment]
Yes, it's this one: https://imballinst.github.io/protosaurus/pr-25/docs/booking.v1#testenumoutside

image

I put it below the "Messages". So, if there are services, messages, and enums, then there will be 3 sections in total. Are we OK with this?

**Review by dio — APPROVED** [review]

**Comment by imballinst** [comment]
Thanks @dio for the review!

**Pull request merged**
